remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"
title: awesome mendix
#longtitle : awesome mendix
description: Bookmark this to keep an eye on my project updates!

toc:
  enabled: true
  h_min:   1
  h_max:   3

# markdown render engine.
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md


#page_width: 800px

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed