remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"
title: awesome mendix
#longtitle : awesome mendix
description: Bookmark this to keep an eye on my project updates!

toc:
  enabled: true
  h_min:   1
  h_max:   3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md


#page_width: 800px

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-include-cache